name: Run Swift File

on:
  push:
    paths:
      - '**.swift'
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Swift code
        run: swift main.swift
